const String floorFilename = 'floor.png';
const String backgroundFilename = 'background.png';
const String leftArrowFilename = "left_arrow.png";
const String rightArrowFilename = "right_arrow.png";
const String upArrowFilename = "up_arrow.png";
const String downArrowFilename = "down_arrow.png";
const String rosantFilename = "rosant.png";
// const String pointSoundFilename = 'audio/point.mp3';
// const String loseSoundFilename = 'audio/lose.mp3';