import 'package:audioplayers/audioplayers.dart';
import 'package:flame/components.dart';
import '/models/scenery/screen.dart';

late Sprite floorSprite;
late Sprite backgroundSprite;
late Sprite leftArrowSprite;
late Sprite rightArrowSprite;
late Sprite upArrowSprite;
late Sprite downArrowSprite;
late Sprite buttonJumpSprite;
late Sprite buttonAttackSprite;
late Sprite rosantRightSprite;
late Sprite rosantLeftSprite;
AudioPlayer player = AudioPlayer();
bool assetsLoaded = false;
Vector2 initialWorldLinearVelocity = Vector2(-4, 0);
double initialBladeAngularVelocity = radians(360);
Vector2 worldLinearVelocity = initialWorldLinearVelocity;
double bladeAngularVelocity = initialBladeAngularVelocity;
double horizon = Screen.worldSize.y/2;